### ISSUE TITLE
Infografía Gestión de Proyectos De Software

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/infografia-Anthony4523-1#2]
![Gestión de proyectos de Software](https://user-images.githubusercontent.com/73609728/132248093-e24f8405-4b8e-4162-b66a-95cdcea48337.png)

**Comment by JeserLeonel** [comment]
**Calificación = 20 ** Excelente.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
